#!/bin/bash
BASE="/c/Users/endri/projects/towingservicequeensnyc"

generate_neighborhood() {
  local slug="$1" name="$2" nickname="$3" zip="$4" lat="$5" lng="$6" landmarks="$7" streets="$8" nearby="$9"
  local dir="$BASE/neighborhoods/$slug"
  mkdir -p "$dir"

  local nick_display=""
  if [ -n "$nickname" ]; then
    nick_display="Also known as $nickname, this"
  else
    nick_display="This"
  fi

  cat > "$dir/index.html" << HTMLEOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Towing Service ${name} Queens NY | 24/7 Tow Truck | (347) 437-0185</title>
<meta name="description" content="Need a tow truck in ${name}, Queens? Towing Service Queens NYC provides 24/7 emergency towing, flatbed towing, roadside assistance in ${name}. Call (347) 437-0185. ZIP ${zip}.">
<link rel="canonical" href="https://towingservicequeensnyc.com/neighborhoods/${slug}/">
<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large">
<meta property="og:type" content="website">
<meta property="og:title" content="Towing Service ${name} Queens NY | 24/7 | (347) 437-0185">
<meta property="og:description" content="24/7 towing and roadside assistance in ${name}, Queens. Call (347) 437-0185.">
<meta property="og:url" content="https://towingservicequeensnyc.com/neighborhoods/${slug}/">
<link rel="stylesheet" href="../../css/style.css">
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"TowingService","name":"Towing Service Queens NYC - ${name}","telephone":"+1-347-437-0185","url":"https://towingservicequeensnyc.com/neighborhoods/${slug}/","address":{"@type":"PostalAddress","streetAddress":"15557 Bayview Ave","addressLocality":"Queens","addressRegion":"NY","postalCode":"11360","addressCountry":"US"},"geo":{"@type":"GeoCoordinates","latitude":${lat},"longitude":${lng}},"openingHoursSpecification":{"@type":"OpeningHoursSpecification","dayOfWeek":["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],"opens":"00:00","closes":"23:59"},"areaServed":{"@type":"Neighborhood","name":"${name}, Queens, NY"},"priceRange":"\\$\\$"}
</script>
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://towingservicequeensnyc.com/"},{"@type":"ListItem","position":2,"name":"Service Areas","item":"https://towingservicequeensnyc.com/neighborhoods/"},{"@type":"ListItem","position":3,"name":"${name}","item":"https://towingservicequeensnyc.com/neighborhoods/${slug}/"}]}
</script>
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"How fast can a tow truck get to ${name}, Queens?","acceptedAnswer":{"@type":"Answer","text":"Our average response time to ${name} is 15-30 minutes. We have tow trucks positioned throughout Queens for the fastest possible response. Call (347) 437-0185 for immediate dispatch."}},{"@type":"Question","name":"What towing services do you offer in ${name}?","acceptedAnswer":{"@type":"Answer","text":"We offer emergency towing, flatbed towing, heavy duty towing, motorcycle towing, roadside assistance, lockout service, jump starts, flat tire changes, fuel delivery, winching and recovery, accident recovery, and junk car removal in ${name}, Queens."}},{"@type":"Question","name":"How much does towing cost in ${name}, Queens?","acceptedAnswer":{"@type":"Answer","text":"Towing costs in ${name} vary based on service type, vehicle size, and distance. We offer competitive, transparent pricing with no hidden fees. Call (347) 437-0185 for a free quote."}},{"@type":"Question","name":"Do you offer 24-hour towing in ${name}?","acceptedAnswer":{"@type":"Answer","text":"Yes! We provide 24/7/365 towing and roadside assistance in ${name}, Queens. Call (347) 437-0185 anytime."}},{"@type":"Question","name":"What ZIP codes do you serve in ${name}?","acceptedAnswer":{"@type":"Answer","text":"We serve ${name} and surrounding areas including ZIP code(s) ${zip}."}}]}
</script>
</head>
<body>
<div class="top-bar"><div class="container"><div class="top-bar-left"><span>24/7 Emergency Towing in ${name}, Queens</span></div><div class="top-bar-right"><a href="tel:+13474370185">Call: (347) 437-0185</a><a href="tel:+13474370185" class="urgent-btn">NEED URGENT TOWING? (347) 437-0185</a></div></div></div>
<header class="header"><div class="container"><a href="/" class="logo"><div class="logo-icon">T</div><div class="logo-text">Towing Service<br>Queens NYC<span>24/7 Emergency Towing</span></div></a><nav class="nav"><button class="menu-toggle" aria-label="Toggle menu"><span></span><span></span><span></span></button><ul class="nav-list"><li><a href="/">Home</a></li><li class="nav-dropdown"><a href="/services/">Services</a><div class="nav-dropdown-content"><a href="/services/emergency-towing/">Emergency Towing</a><a href="/services/flatbed-towing/">Flatbed Towing</a><a href="/services/heavy-duty-towing/">Heavy Duty Towing</a><a href="/services/motorcycle-towing/">Motorcycle Towing</a><a href="/services/roadside-assistance/">Roadside Assistance</a><a href="/services/lockout-service/">Lockout Service</a><a href="/services/jump-start-service/">Jump Start</a><a href="/services/flat-tire-change/">Flat Tire</a><a href="/services/fuel-delivery/">Fuel Delivery</a><a href="/services/winching-recovery/">Winching</a></div></li><li class="nav-dropdown"><a href="/neighborhoods/" class="active">Service Areas</a><div class="nav-dropdown-content"><a href="/neighborhoods/astoria/">Astoria</a><a href="/neighborhoods/flushing/">Flushing</a><a href="/neighborhoods/jamaica/">Jamaica</a><a href="/neighborhoods/long-island-city/">LIC</a><a href="/neighborhoods/jackson-heights/">Jackson Heights</a><a href="/neighborhoods/bayside/">Bayside</a><a href="/neighborhoods/forest-hills/">Forest Hills</a><a href="/neighborhoods/howard-beach/">Howard Beach</a><a href="/neighborhoods/far-rockaway/">Far Rockaway</a></div></li><li><a href="/about.html">About</a></li><li><a href="/contact.html">Contact</a></li></ul></nav><div class="header-cta"><a href="tel:+13474370185">&#9742; (347) 437-0185</a></div></div></header>
<nav class="breadcrumbs"><div class="container"><ul class="breadcrumbs-list"><li><a href="/">Home</a></li><li><a href="/neighborhoods/">Service Areas</a></li><li>${name}</li></ul></div></nav>
<section class="page-hero"><div class="container"><h1><em>Towing Service in <span class="accent">${name}</span>, Queens NY</em></h1><p>${nick_display} Queens neighborhood is fully covered by our 24/7 towing and roadside assistance service. Fast response, transparent pricing, professional operators.</p><a href="tel:+13474370185" class="hero-phone">Call (347) 437-0185</a></div></section>
<section class="content-area"><div class="container"><div class="content-layout">
<main>
<h2>24/7 Tow Truck Service in ${name}, Queens</h2>
<p>Looking for a reliable tow truck in ${name}, Queens? Towing Service Queens NYC provides fast, professional towing and roadside assistance throughout ${name} and surrounding areas. ${nick_display} vibrant Queens neighborhood deserves a towing company that knows its streets, and our drivers navigate ${name} every single day, ensuring the fastest possible response when you need help most.</p>
<p>Whether you have broken down near ${landmarks}, or you are stuck on ${streets}, our tow trucks can reach you in 15-30 minutes. We serve all of ${name} including ZIP code(s) ${zip}, providing comprehensive towing and roadside services around the clock.</p>
<h2>Towing &amp; Roadside Services in ${name}</h2>
<p>We offer the full range of towing and roadside assistance services in ${name}, Queens:</p>
<ul>
<li><strong><a href="/services/emergency-towing/">Emergency Towing</a></strong> — 24/7 emergency tow truck dispatch to ${name}. Response time under 30 minutes.</li>
<li><strong><a href="/services/flatbed-towing/">Flatbed Towing</a></strong> — Safe, damage-free transport for all vehicles including luxury cars and AWD vehicles.</li>
<li><strong><a href="/services/heavy-duty-towing/">Heavy Duty Towing</a></strong> — Towing for trucks, buses, RVs, and commercial vehicles in ${name}.</li>
<li><strong><a href="/services/motorcycle-towing/">Motorcycle Towing</a></strong> — Specialized motorcycle transport with proper strapping equipment.</li>
<li><strong><a href="/services/roadside-assistance/">Roadside Assistance</a></strong> — Jump starts, tire changes, fuel delivery, and more.</li>
<li><strong><a href="/services/lockout-service/">Lockout Service</a></strong> — Locked out? We get you back in without damage.</li>
<li><strong><a href="/services/jump-start-service/">Jump Start Service</a></strong> — Dead battery jump starts on the spot.</li>
<li><strong><a href="/services/flat-tire-change/">Flat Tire Change</a></strong> — Quick tire swap to get you moving safely.</li>
<li><strong><a href="/services/fuel-delivery/">Fuel Delivery</a></strong> — Fuel delivered directly to your location in ${name}.</li>
<li><strong><a href="/services/winching-recovery/">Winching &amp; Recovery</a></strong> — Vehicle recovery from ditches, mud, and snow.</li>
<li><strong><a href="/services/accident-recovery/">Accident Recovery</a></strong> — Professional accident scene vehicle recovery.</li>
<li><strong><a href="/services/junk-car-removal/">Junk Car Removal</a></strong> — Free junk car pickup in ${name}.</li>
</ul>
<h2>Why Choose Us for Towing in ${name}?</h2>
<ul>
<li><strong>Fast Response:</strong> 15-30 minute average response time to ${name}.</li>
<li><strong>24/7 Availability:</strong> We never close. Day, night, holidays — always ready.</li>
<li><strong>Transparent Pricing:</strong> No hidden fees. Upfront quotes before work begins.</li>
<li><strong>Licensed &amp; Insured:</strong> Fully licensed, bonded, and insured.</li>
<li><strong>Modern Fleet:</strong> Flatbed trucks, wheel-lifts, heavy-duty wreckers.</li>
<li><strong>Local Knowledge:</strong> Our drivers know every street in ${name}.</li>
<li><strong>All Vehicles:</strong> Cars, trucks, motorcycles, SUVs, luxury vehicles, commercial.</li>
</ul>
<h2>Frequently Asked Questions</h2>
<div class="faq-list">
<div class="faq-item active"><div class="faq-question">How fast can a tow truck get to ${name}?</div><div class="faq-answer"><div class="faq-answer-inner">Our average response time to ${name} is 15-30 minutes. Call (347) 437-0185 for immediate dispatch.</div></div></div>
<div class="faq-item"><div class="faq-question">What services do you offer in ${name}?</div><div class="faq-answer"><div class="faq-answer-inner">We offer emergency towing, flatbed towing, heavy duty towing, motorcycle towing, roadside assistance, lockout service, jump starts, tire changes, fuel delivery, winching, accident recovery, and junk car removal.</div></div></div>
<div class="faq-item"><div class="faq-question">How much does towing cost in ${name}?</div><div class="faq-answer"><div class="faq-answer-inner">Costs vary by service type, vehicle, and distance. We offer transparent pricing with no hidden fees. Call (347) 437-0185 for a free quote.</div></div></div>
<div class="faq-item"><div class="faq-question">Do you offer 24-hour towing in ${name}?</div><div class="faq-answer"><div class="faq-answer-inner">Yes! 24/7/365 towing and roadside assistance. Call (347) 437-0185 anytime.</div></div></div>
<div class="faq-item"><div class="faq-question">What ZIP codes do you serve in ${name}?</div><div class="faq-answer"><div class="faq-answer-inner">We serve ${name} and surrounding areas including ZIP code(s) ${zip}.</div></div></div>
</div>
<h2>About ${name}, Queens</h2>
<p>${name} is a distinctive neighborhood in Queens, New York${nickname:+, also known as $nickname}. Our drivers know ${name} inside and out — from ${landmarks} to the side streets off ${streets}. Whether you live here or are passing through, call <a href="tel:+13474370185" style="color:#ff4a11;font-weight:700;">(347) 437-0185</a> for fast towing service.</p>
</main>
<aside class="sidebar">
<div class="sidebar-widget sidebar-cta"><h3>Need a Tow in ${name}?</h3><p>Fast 24/7 towing service.</p><a href="tel:+13474370185" class="phone">(347) 437-0185</a><a href="tel:+13474370185" class="btn btn-primary" style="width:100%;">Call Now</a></div>
<div class="sidebar-widget"><h3>Our Services</h3><ul><li><a href="/services/emergency-towing/">Emergency Towing</a></li><li><a href="/services/flatbed-towing/">Flatbed Towing</a></li><li><a href="/services/heavy-duty-towing/">Heavy Duty Towing</a></li><li><a href="/services/roadside-assistance/">Roadside Assistance</a></li><li><a href="/services/lockout-service/">Lockout Service</a></li><li><a href="/services/">View All Services</a></li></ul></div>
<div class="sidebar-widget"><h3>Nearby Areas</h3><ul>${nearby}</ul></div>
</aside>
</div></div></section>
<section class="cta-banner"><div class="container"><h2><em>Need a Tow Truck in ${name}? Call Now!</em></h2><a href="tel:+13474370185" class="phone-number">(347) 437-0185</a><p>24/7 emergency towing in ${name}, Queens.</p><a href="tel:+13474370185" class="btn btn-primary btn-cta">Call For Fast Service</a></div></section>
<footer class="footer"><div class="container"><div class="footer-grid"><div><h3>Towing Service Queens NYC</h3><p style="margin-bottom:16px;font-size:0.9rem;">24/7 towing across all Queens neighborhoods.</p><div class="footer-contact-item"><span class="footer-contact-icon">&#128205;</span><span>15557 Bayview Ave, Queens, NY 11360</span></div><div class="footer-contact-item"><span class="footer-contact-icon">&#128222;</span><a href="tel:+13474370185">(347) 437-0185</a></div></div><div><h3>Services</h3><ul class="footer-links"><li><a href="/services/emergency-towing/">Emergency Towing</a></li><li><a href="/services/flatbed-towing/">Flatbed Towing</a></li><li><a href="/services/heavy-duty-towing/">Heavy Duty Towing</a></li><li><a href="/services/roadside-assistance/">Roadside Assistance</a></li><li><a href="/services/">All Services</a></li></ul></div><div><h3>Areas</h3><ul class="footer-links"><li><a href="/neighborhoods/astoria/">Astoria</a></li><li><a href="/neighborhoods/flushing/">Flushing</a></li><li><a href="/neighborhoods/jamaica/">Jamaica</a></li><li><a href="/neighborhoods/">All Areas</a></li></ul></div><div><h3>Links</h3><ul class="footer-links"><li><a href="/">Home</a></li><li><a href="/about.html">About</a></li><li><a href="/contact.html">Contact</a></li></ul></div></div><div class="footer-bottom"><p>&copy; 2026 Towing Service Queens NYC. | <a href="tel:+13474370185">(347) 437-0185</a></p></div></div></footer>
<div class="mobile-call-bar"><a href="tel:+13474370185">&#128222; Tap to Call (347) 437-0185</a></div>
<script src="../../js/main.js"></script>
</body>
</html>
HTMLEOF
  echo "Created: $slug"
}

# Western Queens missing
generate_neighborhood "sunnyside" "Sunnyside" "Sunnyside Gardens" "11104" "40.7432" "-73.9134" "Sunnyside Arch and Skillman Avenue" "Queens Boulevard and 46th Street" '<li><a href="/neighborhoods/woodside/">Woodside</a></li><li><a href="/neighborhoods/long-island-city/">LIC</a></li><li><a href="/neighborhoods/astoria/">Astoria</a></li><li><a href="/neighborhoods/jackson-heights/">Jackson Heights</a></li>'
generate_neighborhood "woodside" "Woodside" "" "11377" "40.7454" "-73.9026" "Doughboy Plaza and St Sebastian Church" "Roosevelt Avenue and Woodside Avenue" '<li><a href="/neighborhoods/sunnyside/">Sunnyside</a></li><li><a href="/neighborhoods/jackson-heights/">Jackson Heights</a></li><li><a href="/neighborhoods/elmhurst/">Elmhurst</a></li><li><a href="/neighborhoods/maspeth/">Maspeth</a></li>'
generate_neighborhood "ditmars-steinway" "Ditmars Steinway" "Ditmars" "11105" "40.7751" "-73.9109" "Athens Square Park and Steinway Street" "Ditmars Boulevard and 31st Street" '<li><a href="/neighborhoods/astoria/">Astoria</a></li><li><a href="/neighborhoods/astoria-heights/">Astoria Heights</a></li><li><a href="/neighborhoods/steinway/">Steinway</a></li>'
generate_neighborhood "dutch-kills" "Dutch Kills" "" "11101" "40.7478" "-73.9375" "Dutch Kills Green and Queensboro Bridge" "Queens Boulevard and Jackson Avenue" '<li><a href="/neighborhoods/long-island-city/">LIC</a></li><li><a href="/neighborhoods/court-square/">Court Square</a></li><li><a href="/neighborhoods/sunnyside/">Sunnyside</a></li>'
generate_neighborhood "hunters-point" "Hunters Point" "" "11101" "40.7419" "-73.9560" "Gantry Plaza State Park and the waterfront" "Vernon Boulevard and Center Boulevard" '<li><a href="/neighborhoods/long-island-city/">LIC</a></li><li><a href="/neighborhoods/court-square/">Court Square</a></li><li><a href="/neighborhoods/dutch-kills/">Dutch Kills</a></li>'
generate_neighborhood "ravenswood" "Ravenswood" "" "11106" "40.7628" "-73.9377" "Rainey Park and 21st Street" "21st Street and Broadway" '<li><a href="/neighborhoods/astoria/">Astoria</a></li><li><a href="/neighborhoods/long-island-city/">LIC</a></li><li><a href="/neighborhoods/queensbridge/">Queensbridge</a></li>'
generate_neighborhood "queensbridge" "Queensbridge" "QB / The Bridge" "11101" "40.7554" "-73.9430" "Queensbridge Houses and Queensboro Bridge" "21st Street and 41st Avenue" '<li><a href="/neighborhoods/ravenswood/">Ravenswood</a></li><li><a href="/neighborhoods/long-island-city/">LIC</a></li><li><a href="/neighborhoods/astoria/">Astoria</a></li>'
generate_neighborhood "court-square" "Court Square" "" "11101" "40.7472" "-73.9459" "Court Square Park and Citigroup Building" "Jackson Avenue and Court Square" '<li><a href="/neighborhoods/long-island-city/">LIC</a></li><li><a href="/neighborhoods/hunters-point/">Hunters Point</a></li><li><a href="/neighborhoods/dutch-kills/">Dutch Kills</a></li>'
generate_neighborhood "steinway" "Steinway" "" "11103" "40.7714" "-73.9084" "Steinway Street corridor and Steinway Piano Factory" "Steinway Street and Broadway" '<li><a href="/neighborhoods/astoria/">Astoria</a></li><li><a href="/neighborhoods/ditmars-steinway/">Ditmars</a></li><li><a href="/neighborhoods/woodside/">Woodside</a></li>'
generate_neighborhood "astoria-heights" "Astoria Heights" "" "11105" "40.7781" "-73.8967" "St Michael Cemetery and the parks" "Ditmars Boulevard and 46th Street" '<li><a href="/neighborhoods/astoria/">Astoria</a></li><li><a href="/neighborhoods/ditmars-steinway/">Ditmars</a></li><li><a href="/neighborhoods/steinway/">Steinway</a></li>'
generate_neighborhood "old-astoria" "Old Astoria" "" "11102" "40.7740" "-73.9250" "Astoria Park and Hell Gate Bridge" "Shore Boulevard and Astoria Park South" '<li><a href="/neighborhoods/astoria/">Astoria</a></li><li><a href="/neighborhoods/hallets-point/">Hallets Point</a></li><li><a href="/neighborhoods/ditmars-steinway/">Ditmars</a></li>'
generate_neighborhood "hallets-point" "Hallets Point" "Hallets Cove" "11102" "40.7810" "-73.9280" "Hallets Point waterfront development" "Main Avenue and Astoria Boulevard" '<li><a href="/neighborhoods/old-astoria/">Old Astoria</a></li><li><a href="/neighborhoods/astoria/">Astoria</a></li><li><a href="/neighborhoods/ravenswood/">Ravenswood</a></li>'
generate_neighborhood "bowery-bay" "Bowery Bay" "" "11105" "40.7780" "-73.8930" "LaGuardia Airport and Bowery Bay" "19th Avenue and Hazen Street" '<li><a href="/neighborhoods/astoria-heights/">Astoria Heights</a></li><li><a href="/neighborhoods/ditmars-steinway/">Ditmars</a></li><li><a href="/neighborhoods/east-elmhurst/">East Elmhurst</a></li>'

# Central/NE missing
generate_neighborhood "clearview" "Clearview" "" "11361" "40.7780" "-73.7810" "Clearview Golf Course and Clearview Expressway" "Francis Lewis Blvd and 35th Avenue" '<li><a href="/neighborhoods/bayside/">Bayside</a></li><li><a href="/neighborhoods/whitestone/">Whitestone</a></li><li><a href="/neighborhoods/bay-terrace/">Bay Terrace</a></li>'
generate_neighborhood "hillcrest" "Hillcrest" "" "11432" "40.7220" "-73.8050" "St John University and Hillcrest Jewish Center" "Union Turnpike and 164th Street" '<li><a href="/neighborhoods/fresh-meadows/">Fresh Meadows</a></li><li><a href="/neighborhoods/jamaica-estates/">Jamaica Estates</a></li><li><a href="/neighborhoods/pomonok/">Pomonok</a></li>'
generate_neighborhood "linden-hill" "Linden Hill" "" "11354" "40.7710" "-73.8220" "Linden Hill residential area" "Linden Place and 29th Avenue" '<li><a href="/neighborhoods/flushing/">Flushing</a></li><li><a href="/neighborhoods/whitestone/">Whitestone</a></li><li><a href="/neighborhoods/college-point/">College Point</a></li>'
generate_neighborhood "malba" "Malba" "" "11357" "40.7920" "-73.8200" "Malba waterfront and Powells Cove" "Malba Drive and 14th Avenue" '<li><a href="/neighborhoods/whitestone/">Whitestone</a></li><li><a href="/neighborhoods/beechhurst/">Beechhurst</a></li><li><a href="/neighborhoods/college-point/">College Point</a></li>'
generate_neighborhood "beechhurst" "Beechhurst" "" "11357" "40.7930" "-73.8100" "Cryder Point and Beechhurst waterfront" "Totten Avenue and 160th Street" '<li><a href="/neighborhoods/whitestone/">Whitestone</a></li><li><a href="/neighborhoods/malba/">Malba</a></li><li><a href="/neighborhoods/bay-terrace/">Bay Terrace</a></li>'
generate_neighborhood "pomonok" "Pomonok" "" "11365" "40.7310" "-73.8050" "Pomonok Houses and Kissena Corridor Park" "Jewel Avenue and Kissena Boulevard" '<li><a href="/neighborhoods/flushing/">Flushing</a></li><li><a href="/neighborhoods/hillcrest/">Hillcrest</a></li><li><a href="/neighborhoods/fresh-meadows/">Fresh Meadows</a></li>'
generate_neighborhood "utopia" "Utopia" "Utopia Estates" "11365" "40.7340" "-73.7980" "Utopia Playground and residential streets" "Utopia Parkway and 73rd Avenue" '<li><a href="/neighborhoods/fresh-meadows/">Fresh Meadows</a></li><li><a href="/neighborhoods/oakland-gardens/">Oakland Gardens</a></li><li><a href="/neighborhoods/pomonok/">Pomonok</a></li>'
generate_neighborhood "queensboro-hill" "Queensboro Hill" "" "11355" "40.7490" "-73.8230" "Kissena Park and Queensboro Hill playground" "Kissena Boulevard and Barclay Avenue" '<li><a href="/neighborhoods/flushing/">Flushing</a></li><li><a href="/neighborhoods/kew-gardens-hills/">KGH</a></li><li><a href="/neighborhoods/pomonok/">Pomonok</a></li>'
generate_neighborhood "willets-point" "Willets Point" "The Iron Triangle" "11368" "40.7610" "-73.8450" "Citi Field and former Iron Triangle auto shops" "126th Street and Roosevelt Avenue" '<li><a href="/neighborhoods/corona/">Corona</a></li><li><a href="/neighborhoods/flushing/">Flushing</a></li><li><a href="/neighborhoods/east-elmhurst/">East Elmhurst</a></li>'

# SE Queens missing
generate_neighborhood "addisleigh-park" "Addisleigh Park" "" "11434" "40.6960" "-73.7600" "historic Addisleigh Park residential district" "Linden Boulevard and Murdock Avenue" '<li><a href="/neighborhoods/st-albans/">St. Albans</a></li><li><a href="/neighborhoods/jamaica/">Jamaica</a></li><li><a href="/neighborhoods/hollis/">Hollis</a></li>'
generate_neighborhood "baisley-park" "Baisley Park" "" "11434" "40.6830" "-73.7870" "Baisley Pond Park and nature trails" "Baisley Boulevard and Sutphin Boulevard" '<li><a href="/neighborhoods/south-jamaica/">South Jamaica</a></li><li><a href="/neighborhoods/jamaica/">Jamaica</a></li><li><a href="/neighborhoods/rochdale/">Rochdale</a></li>'
generate_neighborhood "brookville" "Brookville" "" "11422" "40.6640" "-73.7470" "Brookville Park and JFK Airport area" "Brookville Boulevard and 147th Avenue" '<li><a href="/neighborhoods/rosedale/">Rosedale</a></li><li><a href="/neighborhoods/laurelton/">Laurelton</a></li><li><a href="/neighborhoods/springfield-gardens/">Springfield Gardens</a></li>'
generate_neighborhood "cambria-heights" "Cambria Heights" "" "11411" "40.6932" "-73.7371" "Cambria Heights playground" "Linden Boulevard and Francis Lewis Boulevard" '<li><a href="/neighborhoods/queens-village/">Queens Village</a></li><li><a href="/neighborhoods/laurelton/">Laurelton</a></li><li><a href="/neighborhoods/st-albans/">St. Albans</a></li>'
generate_neighborhood "hollis" "Hollis" "Home of Hip Hop" "11423" "40.7117" "-73.7638" "birthplace of Run-DMC on Hollis Avenue" "Hillside Avenue and Francis Lewis Boulevard" '<li><a href="/neighborhoods/jamaica/">Jamaica</a></li><li><a href="/neighborhoods/hollis-hills/">Hollis Hills</a></li><li><a href="/neighborhoods/queens-village/">Queens Village</a></li>'
generate_neighborhood "hollis-hills" "Hollis Hills" "" "11427" "40.7260" "-73.7570" "Cunningham Park and residential area" "Union Turnpike and 210th Street" '<li><a href="/neighborhoods/hollis/">Hollis</a></li><li><a href="/neighborhoods/queens-village/">Queens Village</a></li><li><a href="/neighborhoods/oakland-gardens/">Oakland Gardens</a></li>'
generate_neighborhood "jamaica-hills" "Jamaica Hills" "" "11432" "40.7150" "-73.7930" "St John University and King Manor Museum" "Hillside Avenue and Parsons Boulevard" '<li><a href="/neighborhoods/jamaica/">Jamaica</a></li><li><a href="/neighborhoods/jamaica-estates/">Jamaica Estates</a></li><li><a href="/neighborhoods/briarwood/">Briarwood</a></li>'
generate_neighborhood "laurelton" "Laurelton" "" "11413" "40.6775" "-73.7453" "Laurelton LIRR station" "Francis Lewis Blvd and Merrick Boulevard" '<li><a href="/neighborhoods/springfield-gardens/">Springfield Gardens</a></li><li><a href="/neighborhoods/rosedale/">Rosedale</a></li><li><a href="/neighborhoods/cambria-heights/">Cambria Heights</a></li>'
generate_neighborhood "meadowmere" "Meadowmere" "" "11422" "40.6380" "-73.7500" "JFK Airport border area" "Rockaway Blvd and Brookville Boulevard" '<li><a href="/neighborhoods/rosedale/">Rosedale</a></li><li><a href="/neighborhoods/brookville/">Brookville</a></li><li><a href="/neighborhoods/far-rockaway/">Far Rockaway</a></li>'
generate_neighborhood "queens-village" "Queens Village" "QV" "11427, 11428, 11429" "40.7264" "-73.7416" "Queens Village LIRR station" "Hillside Avenue and Springfield Boulevard" '<li><a href="/neighborhoods/hollis/">Hollis</a></li><li><a href="/neighborhoods/cambria-heights/">Cambria Heights</a></li><li><a href="/neighborhoods/bellerose/">Bellerose</a></li>'
generate_neighborhood "rochdale" "Rochdale" "Rochdale Village" "11434" "40.6830" "-73.7740" "Rochdale Village shopping center" "Guy Brewer Blvd and Baisley Boulevard" '<li><a href="/neighborhoods/south-jamaica/">South Jamaica</a></li><li><a href="/neighborhoods/baisley-park/">Baisley Park</a></li><li><a href="/neighborhoods/springfield-gardens/">Springfield Gardens</a></li>'
generate_neighborhood "rosedale" "Rosedale" "" "11422" "40.6596" "-73.7375" "Rosedale LIRR station and Brookville Park" "Francis Lewis Blvd and Sunrise Highway" '<li><a href="/neighborhoods/laurelton/">Laurelton</a></li><li><a href="/neighborhoods/brookville/">Brookville</a></li><li><a href="/neighborhoods/meadowmere/">Meadowmere</a></li>'
generate_neighborhood "south-jamaica" "South Jamaica" "Southside" "11433, 11434, 11436" "40.6910" "-73.7920" "York College CUNY and South Jamaica Houses" "Sutphin Boulevard and South Road" '<li><a href="/neighborhoods/jamaica/">Jamaica</a></li><li><a href="/neighborhoods/rochdale/">Rochdale</a></li><li><a href="/neighborhoods/baisley-park/">Baisley Park</a></li>'
generate_neighborhood "springfield-gardens" "Springfield Gardens" "Springfield" "11413, 11434" "40.6649" "-73.7619" "Springfield Park and residential blocks" "Merrick Blvd and Springfield Boulevard" '<li><a href="/neighborhoods/laurelton/">Laurelton</a></li><li><a href="/neighborhoods/rosedale/">Rosedale</a></li><li><a href="/neighborhoods/brookville/">Brookville</a></li>'
generate_neighborhood "st-albans" "St. Albans" "" "11412" "40.6896" "-73.7652" "St Albans Park and historic community" "Linden Boulevard and Farmers Boulevard" '<li><a href="/neighborhoods/hollis/">Hollis</a></li><li><a href="/neighborhoods/cambria-heights/">Cambria Heights</a></li><li><a href="/neighborhoods/addisleigh-park/">Addisleigh Park</a></li>'

# SW Queens missing
generate_neighborhood "broad-channel" "Broad Channel" "Venice of New York" "11693" "40.6030" "-73.8200" "Jamaica Bay Wildlife Refuge" "Cross Bay Boulevard and Noel Road" '<li><a href="/neighborhoods/howard-beach/">Howard Beach</a></li><li><a href="/neighborhoods/rockaway-beach/">Rockaway Beach</a></li><li><a href="/neighborhoods/rockaway-park/">Rockaway Park</a></li>'
generate_neighborhood "hamilton-beach" "Hamilton Beach" "" "11414" "40.6520" "-73.8440" "Hamilton Beach and Jamaica Bay" "102nd Street and 165th Avenue" '<li><a href="/neighborhoods/howard-beach/">Howard Beach</a></li><li><a href="/neighborhoods/old-howard-beach/">Old Howard Beach</a></li><li><a href="/neighborhoods/lindenwood/">Lindenwood</a></li>'
generate_neighborhood "old-howard-beach" "Old Howard Beach" "" "11414" "40.6600" "-73.8470" "Charles Memorial Park" "159th Avenue and 84th Street" '<li><a href="/neighborhoods/howard-beach/">Howard Beach</a></li><li><a href="/neighborhoods/hamilton-beach/">Hamilton Beach</a></li><li><a href="/neighborhoods/lindenwood/">Lindenwood</a></li>'

# Rockaways missing
generate_neighborhood "far-rockaway" "Far Rockaway" "Far Rock" "11691" "40.6005" "-73.7551" "Far Rockaway LIRR station and Bayswater Park" "Beach 20th Street and Mott Avenue" '<li><a href="/neighborhoods/edgemere/">Edgemere</a></li><li><a href="/neighborhoods/arverne/">Arverne</a></li><li><a href="/neighborhoods/rockaway-beach/">Rockaway Beach</a></li>'
generate_neighborhood "arverne" "Arverne" "" "11692" "40.5918" "-73.7935" "Arverne by the Sea and the boardwalk" "Beach 67th St and Rockaway Beach Blvd" '<li><a href="/neighborhoods/far-rockaway/">Far Rockaway</a></li><li><a href="/neighborhoods/edgemere/">Edgemere</a></li><li><a href="/neighborhoods/rockaway-beach/">Rockaway Beach</a></li>'
generate_neighborhood "rockaway-beach" "Rockaway Beach" "The Rockaways / Irish Riviera" "11693" "40.5830" "-73.8130" "Rockaway Beach boardwalk and Beach 116th" "Rockaway Beach Blvd and Beach Channel Dr" '<li><a href="/neighborhoods/rockaway-park/">Rockaway Park</a></li><li><a href="/neighborhoods/arverne/">Arverne</a></li><li><a href="/neighborhoods/hammels/">Hammels</a></li>'
generate_neighborhood "rockaway-park" "Rockaway Park" "" "11694" "40.5790" "-73.8380" "Rockaway Park Beach" "Beach 116th St and Newport Avenue" '<li><a href="/neighborhoods/rockaway-beach/">Rockaway Beach</a></li><li><a href="/neighborhoods/belle-harbor/">Belle Harbor</a></li><li><a href="/neighborhoods/seaside/">Seaside</a></li>'
generate_neighborhood "belle-harbor" "Belle Harbor" "" "11694" "40.5710" "-73.8470" "Belle Harbor beach community" "Beach 130th St and Newport Avenue" '<li><a href="/neighborhoods/rockaway-park/">Rockaway Park</a></li><li><a href="/neighborhoods/neponsit/">Neponsit</a></li><li><a href="/neighborhoods/breezy-point/">Breezy Point</a></li>'
generate_neighborhood "neponsit" "Neponsit" "" "11694" "40.5680" "-73.8580" "Neponsit Beach Club and gated community" "Beach 142nd St and Rockaway Beach Blvd" '<li><a href="/neighborhoods/belle-harbor/">Belle Harbor</a></li><li><a href="/neighborhoods/breezy-point/">Breezy Point</a></li><li><a href="/neighborhoods/roxbury/">Roxbury</a></li>'
generate_neighborhood "breezy-point" "Breezy Point" "The Breezy / Irish Riviera" "11697" "40.5560" "-73.9220" "Breezy Point Tip and Fort Tilden" "Rockaway Point Boulevard" '<li><a href="/neighborhoods/neponsit/">Neponsit</a></li><li><a href="/neighborhoods/roxbury/">Roxbury</a></li><li><a href="/neighborhoods/belle-harbor/">Belle Harbor</a></li>'
generate_neighborhood "edgemere" "Edgemere" "" "11691" "40.5960" "-73.7670" "Edgemere Park and LIRR station" "Beach 32nd St and Rockaway Freeway" '<li><a href="/neighborhoods/far-rockaway/">Far Rockaway</a></li><li><a href="/neighborhoods/arverne/">Arverne</a></li><li><a href="/neighborhoods/hammels/">Hammels</a></li>'
generate_neighborhood "hammels" "Hammels" "Hammels" "11693" "40.5880" "-73.8020" "Hammel Houses and the oceanfront" "Beach 84th St and Rockaway Beach Blvd" '<li><a href="/neighborhoods/arverne/">Arverne</a></li><li><a href="/neighborhoods/rockaway-beach/">Rockaway Beach</a></li><li><a href="/neighborhoods/seaside/">Seaside</a></li>'
generate_neighborhood "seaside" "Seaside" "" "11694" "40.5800" "-73.8290" "Seaside Park and beachfront" "Beach 108th St and Rockaway Beach Blvd" '<li><a href="/neighborhoods/rockaway-beach/">Rockaway Beach</a></li><li><a href="/neighborhoods/rockaway-park/">Rockaway Park</a></li><li><a href="/neighborhoods/hammels/">Hammels</a></li>'
generate_neighborhood "roxbury" "Roxbury" "" "11697" "40.5600" "-73.8850" "Fort Tilden and Jacob Riis Park" "Rockaway Point Boulevard" '<li><a href="/neighborhoods/breezy-point/">Breezy Point</a></li><li><a href="/neighborhoods/neponsit/">Neponsit</a></li><li><a href="/neighborhoods/belle-harbor/">Belle Harbor</a></li>'

# Other missing
generate_neighborhood "blissville" "Blissville" "The Dead Zone" "11101" "40.7370" "-73.9350" "Calvary Cemetery and industrial area" "Greenpoint Avenue and Review Avenue" '<li><a href="/neighborhoods/long-island-city/">LIC</a></li><li><a href="/neighborhoods/sunnyside/">Sunnyside</a></li><li><a href="/neighborhoods/maspeth/">Maspeth</a></li>'
generate_neighborhood "cunningham-heights" "Cunningham Heights" "" "11365" "40.7390" "-73.7830" "Cunningham Park hiking trails" "Union Turnpike and Francis Lewis Blvd" '<li><a href="/neighborhoods/fresh-meadows/">Fresh Meadows</a></li><li><a href="/neighborhoods/utopia/">Utopia</a></li><li><a href="/neighborhoods/oakland-gardens/">Oakland Gardens</a></li>'
generate_neighborhood "electchester" "Electchester" "" "11375" "40.7230" "-73.8470" "Electchester co-op community" "Jewel Avenue and Main Street" '<li><a href="/neighborhoods/kew-gardens-hills/">KGH</a></li><li><a href="/neighborhoods/fresh-meadows/">Fresh Meadows</a></li><li><a href="/neighborhoods/forest-hills/">Forest Hills</a></li>'
generate_neighborhood "north-shore-towers" "North Shore Towers" "" "11005" "40.7550" "-73.7250" "North Shore Towers gated community" "Grand Central Pkwy and Little Neck Pkwy" '<li><a href="/neighborhoods/glen-oaks/">Glen Oaks</a></li><li><a href="/neighborhoods/floral-park/">Floral Park</a></li><li><a href="/neighborhoods/little-neck/">Little Neck</a></li>'

echo "=== ALL NEIGHBORHOODS DONE ==="
